#!/bin/bash
set -eou pipefail

DEVICE=$DEVICE # /dev/nvme0n1
KERNEL=$KERNEL # lts | edge

echo '
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
' > /etc/apk/repositories

setup-alpine -q

export BOOT_SIZE=128
setup-disk \
    -v \
    -s 0 \
    -k $KERNEL \
    -e \
    -m sys \
    $DEVICE
